/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin.forgot-password'
import { Route as AdminIncompleteOrdersRouteImport } from './routes/admin.incomplete-orders'
import { Route as AdminLandingRouteImport } from './routes/admin.landing'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMenuCategoriesRouteImport } from './routes/admin.menu-categories'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminResetPasswordRouteImport } from './routes/admin.reset-password'
import { Route as AdminSiteContentRouteImport } from './routes/admin.site-content'
import { Route as LandingIndexRouteImport } from './routes/landing.index'
import { Route as LandingSlugRouteImport } from './routes/landing.$slug'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'
import { Route as ApiPublicTelegramFlushLeadsRouteImport } from './routes/api/public/telegram/flush-leads'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIncompleteOrdersRoute = AdminIncompleteOrdersRouteImport.update({
  id: '/incomplete-orders',
  path: '/incomplete-orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLandingRoute = AdminLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuCategoriesRoute = AdminMenuCategoriesRouteImport.update({
  id: '/menu-categories',
  path: '/menu-categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteContentRoute = AdminSiteContentRouteImport.update({
  id: '/site-content',
  path: '/site-content',
  getParentRoute: () => AdminRoute,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRoute,
} as any)
const LandingSlugRoute = LandingSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LandingRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicTelegramFlushLeadsRoute =
  ApiPublicTelegramFlushLeadsRouteImport.update({
    id: '/api/public/telegram/flush-leads',
    path: '/api/public/telegram/flush-leads',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/landing': typeof LandingRouteWithChildren
  '/order-success': typeof OrderSuccessRoute
  '/search': typeof SearchRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/incomplete-orders': typeof AdminIncompleteOrdersRoute
  '/admin/landing': typeof AdminLandingRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu-categories': typeof AdminMenuCategoriesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/site-content': typeof AdminSiteContentRoute
  '/landing/$slug': typeof LandingSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/landing/': typeof LandingIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/api/public/telegram/flush-leads': typeof ApiPublicTelegramFlushLeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/order-success': typeof OrderSuccessRoute
  '/search': typeof SearchRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/incomplete-orders': typeof AdminIncompleteOrdersRoute
  '/admin/landing': typeof AdminLandingRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu-categories': typeof AdminMenuCategoriesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/site-content': typeof AdminSiteContentRoute
  '/landing/$slug': typeof LandingSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/landing': typeof LandingIndexRoute
  '/products': typeof ProductsIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/api/public/telegram/flush-leads': typeof ApiPublicTelegramFlushLeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/landing': typeof LandingRouteWithChildren
  '/order-success': typeof OrderSuccessRoute
  '/search': typeof SearchRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/incomplete-orders': typeof AdminIncompleteOrdersRoute
  '/admin/landing': typeof AdminLandingRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu-categories': typeof AdminMenuCategoriesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/site-content': typeof AdminSiteContentRoute
  '/landing/$slug': typeof LandingSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/landing/': typeof LandingIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/api/public/telegram/flush-leads': typeof ApiPublicTelegramFlushLeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/landing'
    | '/order-success'
    | '/search'
    | '/shipping-policy'
    | '/terms'
    | '/wishlist'
    | '/admin/admins'
    | '/admin/forgot-password'
    | '/admin/incomplete-orders'
    | '/admin/landing'
    | '/admin/login'
    | '/admin/menu-categories'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/reset-password'
    | '/admin/site-content'
    | '/landing/$slug'
    | '/products/$slug'
    | '/admin/'
    | '/landing/'
    | '/products/'
    | '/admin/orders/$id'
    | '/admin/orders/'
    | '/api/public/telegram/flush-leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/order-success'
    | '/search'
    | '/shipping-policy'
    | '/terms'
    | '/wishlist'
    | '/admin/admins'
    | '/admin/forgot-password'
    | '/admin/incomplete-orders'
    | '/admin/landing'
    | '/admin/login'
    | '/admin/menu-categories'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/reset-password'
    | '/admin/site-content'
    | '/landing/$slug'
    | '/products/$slug'
    | '/admin'
    | '/landing'
    | '/products'
    | '/admin/orders/$id'
    | '/admin/orders'
    | '/api/public/telegram/flush-leads'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/landing'
    | '/order-success'
    | '/search'
    | '/shipping-policy'
    | '/terms'
    | '/wishlist'
    | '/admin/admins'
    | '/admin/forgot-password'
    | '/admin/incomplete-orders'
    | '/admin/landing'
    | '/admin/login'
    | '/admin/menu-categories'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/reset-password'
    | '/admin/site-content'
    | '/landing/$slug'
    | '/products/$slug'
    | '/admin/'
    | '/landing/'
    | '/products/'
    | '/admin/orders/$id'
    | '/admin/orders/'
    | '/api/public/telegram/flush-leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  LandingRoute: typeof LandingRouteWithChildren
  OrderSuccessRoute: typeof OrderSuccessRoute
  SearchRoute: typeof SearchRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  TermsRoute: typeof TermsRoute
  WishlistRoute: typeof WishlistRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ApiPublicTelegramFlushLeadsRoute: typeof ApiPublicTelegramFlushLeadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/incomplete-orders': {
      id: '/admin/incomplete-orders'
      path: '/incomplete-orders'
      fullPath: '/admin/incomplete-orders'
      preLoaderRoute: typeof AdminIncompleteOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/landing': {
      id: '/admin/landing'
      path: '/landing'
      fullPath: '/admin/landing'
      preLoaderRoute: typeof AdminLandingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu-categories': {
      id: '/admin/menu-categories'
      path: '/menu-categories'
      fullPath: '/admin/menu-categories'
      preLoaderRoute: typeof AdminMenuCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site-content': {
      id: '/admin/site-content'
      path: '/site-content'
      fullPath: '/admin/site-content'
      preLoaderRoute: typeof AdminSiteContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/landing/': {
      id: '/landing/'
      path: '/'
      fullPath: '/landing/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/landing/$slug': {
      id: '/landing/$slug'
      path: '/$slug'
      fullPath: '/landing/$slug'
      preLoaderRoute: typeof LandingSlugRouteImport
      parentRoute: typeof LandingRoute
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/telegram/flush-leads': {
      id: '/api/public/telegram/flush-leads'
      path: '/api/public/telegram/flush-leads'
      fullPath: '/api/public/telegram/flush-leads'
      preLoaderRoute: typeof ApiPublicTelegramFlushLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminIncompleteOrdersRoute: typeof AdminIncompleteOrdersRoute
  AdminLandingRoute: typeof AdminLandingRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMenuCategoriesRoute: typeof AdminMenuCategoriesRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSiteContentRoute: typeof AdminSiteContentRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminsRoute: AdminAdminsRoute,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminIncompleteOrdersRoute: AdminIncompleteOrdersRoute,
  AdminLandingRoute: AdminLandingRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMenuCategoriesRoute: AdminMenuCategoriesRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSiteContentRoute: AdminSiteContentRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LandingRouteChildren {
  LandingSlugRoute: typeof LandingSlugRoute
  LandingIndexRoute: typeof LandingIndexRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingSlugRoute: LandingSlugRoute,
  LandingIndexRoute: LandingIndexRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  LandingRoute: LandingRouteWithChildren,
  OrderSuccessRoute: OrderSuccessRoute,
  SearchRoute: SearchRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  TermsRoute: TermsRoute,
  WishlistRoute: WishlistRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ApiPublicTelegramFlushLeadsRoute: ApiPublicTelegramFlushLeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
